name: depoware
description: Projekat za praksu.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  multi_select_flutter:
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core:
  cloud_firestore: ^4.3.1
  lottie: ^2.1.0
  firebase_auth:
  font_awesome_flutter:
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
