// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT55eB-EcWSe27A3rPMUJYbVs_fy-80CI',
    appId: '1:351769256856:web:402f0e303983d128ef81ed',
    messagingSenderId: '351769256856',
    projectId: 'prodajaodjece-2102b',
    authDomain: 'prodajaodjece-2102b.firebaseapp.com',
    databaseURL: 'https://prodajaodjece-2102b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prodajaodjece-2102b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAstB7zDd-39h28ZUGprOpc9AmLbUdPUk',
    appId: '1:351769256856:android:c83dfdeda15395e9ef81ed',
    messagingSenderId: '351769256856',
    projectId: 'prodajaodjece-2102b',
    databaseURL: 'https://prodajaodjece-2102b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prodajaodjece-2102b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gcYHdioq0WEsZwYSnQb-YNm04mKDJg4',
    appId: '1:351769256856:ios:e466c8d140bfeebaef81ed',
    messagingSenderId: '351769256856',
    projectId: 'prodajaodjece-2102b',
    databaseURL: 'https://prodajaodjece-2102b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prodajaodjece-2102b.appspot.com',
    iosClientId: '351769256856-st0k5i5jsr4jpan219mfboj4vbndkspm.apps.googleusercontent.com',
    iosBundleId: 'com.example.prodajaodjece',
  );
}
